# Generated by Django 4.1.7 on 2023-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edushedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.CharField(max_length=6),
        ),
    ]
